### ISSUE TITLE
new dev mode behaviour?

### ISSUE THREAD

**Issue by tom-c** [nystudio107/craft-twigpack#32] opened 2019-10-11 15:45 UTC
Not sure if it's me being daft but it seems that the latest version of Twigpack assumes that you're running 'hot' from Webpack at all times when in local dev? 

My experience before I ran the recent updates was that Twigpack would allow me to run using local files if webpack wasn't running (thus allowing for testing of builds). Now it seems I have to switch it on and off in the config to be able to test a fresh build.

Assume Twigpack was testing for the webpack devServer and falling back to localFiles on 404 which doesn't seem to be the case now.

I jumped from v1.1.8 to 1.1.10 in the latest update

Any ideas? Thank you.

**Comment by keyurshah** [comment] 2019-10-12 17:34
I'm having broken css and js as well with the latest build.  It's breaking when viewing web pages directly and as well with laravel mix (browsersync) .

Thanks.

**Comment by khalwat** [comment] 2019-10-15 14:49
This is a result of:

https://github.com/nystudio107/craft-twigpack/pull/26

https://github.com/nystudio107/craft-twigpack/issues/23

**Comment by khalwat** [comment] 2019-10-15 14:50
I'll probably just go in and revert it.

**Comment by khalwat** [comment] 2019-10-15 15:14
So I'm wrong, the issue is actually from this PR -> https://github.com/nystudio107/craft-twigpack/pull/29

**Comment by khalwat** [comment] 2019-10-15 15:19
Fixed in https://github.com/nystudio107/craft-twigpack/commit/19960099587f3373c6770610b88cd91852887d9a

**Closed as completed by khalwat** 2019-10-15 15:19 UTC

**Comment by khalwat** [comment] 2019-10-15 15:30
Released as 1.1.11 -> https://github.com/nystudio107/craft-twigpack/releases/tag/1.1.11
